scanner_path = "/opt/scanner"

[storage]
    type = "posix"
    db_path = "/opt/scanner-db"

# [storage]
#     type = "gcs"
#     key_path = "/path/to/gcs.key"
#     cert_path = "/path/to/gcs.cert"
#     bucket = "gcs-bucket"

[network]
    master = "localhost"
    master_port = "15555"
    worker_port = "15556"
