language: python
python:
- '3.5'
sudo: required
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
env:
  global:
  - BUILD_TYPE=cpu
  - DOCKER_REPO=scannerresearch/scanner
  - DOCKER_TEST_REPO=scannerresearch/test-builds
  - DOCKER_EMAIL=wcrichto@cs.stanford.edu
  - DOCKER_USER=wcrichto
  - secure: "dns3TiHRE95fJhkEC2eBgTF1onubKzDNZ2SybvDC0tqDGczU8e5IXLsmwgfkrNGEH/x0nhCVdIak0NA0BBUdAhK3oldNMHfo/XanGVF40i+9mm6FlJeXEXkiRNTdGfDknyVIakrPKkvWiJvsAWn276yfN0u3JB2Jug27DkfPc5Kr6PJV8oOelr06xhfetmiCIzpSwtc3BZWaH3U+LkdVYNDawjqKGVTQs9R/YlwdcSbGt87boLXXwTkwysMf8hgnz+E2nAdkWPBgsTWY+J0TH+OfVUHMmdDuDuCZPwx5Fj2GoKOFec5CSZLJshTb07rLiCWjbGOo8Wofwjem0P4cj4sR4JByJbHQHL480+/NHFrg1DzpzGxFOv+pycsrJQ3DMk0dvbpLp1d9kj9dgtyRasDaunitSBOyC7+lYJvP2WmiiX64jdgqGDvI3jTc8Xkc1HeqieVJvxE5/loD/9f4CWd51fOGanJUvfLHZ2PABYqHYLAEEGyqvEPUkccXEjc0VfJ9azErhuKYHnnvr2ZoPC2ZZir7oqXdUcYbtkr+TLO0CPu1TSD45+Xe1CgqWzqA5/rxogINrmA/qYFE1nyk/U93ggkpf4jge5c/e8x3Mrb/XxHMIH3NvByAkvwlYRXmT06g8dOTnPUIk6lHi6pB5ok1WPxfpj/63rKs3FSmUIk="
install:
- sudo apt-get update
- sudo apt-get install -y doxygen graphviz
- pip3 install requests[security] --upgrade
jobs:
  include:
    - stage: "Test build"
      script: "travis_retry ./scripts/travis-build.sh"
    # - stage: "Test build"
    #   language: generic
    #   services:
    #     addons:
    #   install:
    #     pip3 install requests[security] --upgrade
    #   script: "travis_retry ./scripts/travis-osx-build.sh"
    #   os: osx
    - stage: test
      script: "travis_retry ./scripts/travis-test.sh"
      env: TEST_TYPE=cpp
    - stage: test
      script: "travis_retry ./scripts/travis-test.sh"
      env: TEST_TYPE=tutorials
    - stage: test
      script: "travis_retry ./scripts/travis-test.sh"
      env: TEST_TYPE=integration
    - stage: build
      script: "travis_retry ./scripts/travis-build.sh"
      after_success: "travis_retry ./scripts/travis-publish.sh"
      env:
        - BUILD_TYPE=cpu
    - stage: build
      script: "travis_retry ./scripts/travis-build.sh"
      env:
        - BUILD_TYPE=gpu-9.0-cudnn7
    - stage: build
      script: "travis_retry ./scripts/travis-build.sh"
      env:
        - BUILD_TYPE=gpu-9.1-cudnn7
    - stage: build
      script: "travis_retry ./scripts/travis-build.sh"
      env:
        - BUILD_TYPE=gpu-10.1-cudnn7
